services:
  axonserver:
    image: "axoniq/axonserver:latest"
    environment:
      - "AXONIQ_AXONSERVER_STANDALONE=TRUE"
    ports:
      - "8024:8024"
      - "8124:8124"
  users-db:
    image: mysql:8.0
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_DATABASE: users_db
    ports:
      - "18000:3306"

