services:
  axonserver:
    image: "axoniq/axonserver:latest"
    environment:
      - "AXONIQ_AXONSERVER_STANDALONE=TRUE"
    ports:
      - "8024:8024"
      - "8124:8124"
#  ventes_microservice_db:
#    image: mysql:8.0
#    environment:
#      MYSQL_ROOT_PASSWORD: root
#      MYSQL_DATABASE: ventes_microservice
#    ports:
#      - "3306:3306"
