global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'boutique-microservice'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['boutique-microservice:8082']

  - job_name: 'ventes-microservice'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['ventes-microservice:8081']

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']