spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: products-microservice
          uri: lb://ProductMicroservice
          predicates:
            - Path=/products/**
        - id: users-microservice
          uri: lb://users-microservice
          predicates:
            - Path=/api/users/**
        - id: cagnottes-microservice-donations
          uri: lb://cagnotte-microservice
          predicates:
            - Path=/api/donations/**
        - id: cagnottes-microservice-cagnottes
          uri: lb://cagnotte-microservice
          predicates:
            - Path=/api/cagnottes/**
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/
  logging:
    level:
      org.springframework: DEBUG
      org.springframework.cloud.gateway: DEBUG