spring:
  application:
    name: boutique-microservice # Name for identification in Eureka
  cloud:
    config:
      uri: http://config-server:8888
      fail-fast: true
      import: "configserver:"
      import-check:
        enabled: true
  datasource:
    url: jdbc:mysql://boutique-db:3306/boutique_db
    username: root
    password: ""
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect


axon:
  axonserver:
    servers: axon-server:8124
  eventhandling:
    processors:
      default:
        mode: tracking
        source: eventStore
        initial-segment-count: 1
  eventstore:
    jpa:
      schema-generation:
        enabled: true
        sequence-style-generator: org.hibernate.id.enhanced.TableGenerator
    persistence:
      sql:
        create-token-table: true
        create-event-table: true
    jdbc:
      sql:
        dialect: mysql

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka # Eureka Server URL

management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    endpoint: http://zipkin:9411/api/v2/spans # Zipkin Server URL

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.axonframework.eventhandling: DEBUG
    org.axonframework.commandhandling: DEBUGw
