spring:
  application:
    name: DeliveryMicroservice

  datasource:
    url: ${JDBC_DATABASE_URL:jdbc:mysql://localhost:3306/delivery?serverTimezone=UTC}
    username: ${JDBC_DATABASE_USERNAME:root}
    password: ${JDBC_DATABASE_PASSWORD:seif2001}
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        id:
          new_generator_mappings: true

  error:
    handling:
      http-status-in-json-response: true
      exception-logging: NO_LOGGING
      full-stacktrace-http-statuses: 5xx
      log-levels:
        5xx: ERROR

  doc:
    pathsToMatch: /, /api/**

  management:
    tracing:
      sampling:
        probability: 1.0 # Taux d'échantillonnage pour la traçabilité (1.0 signifie que toutes les requêtes seront tracées)
    zipkin:
      endpoint: http://localhost:9411/api/v2/spans # URL du serveur Zipkin pour collecter et visualiser les traces

server:
  port: 8087
  address: 0.0.0.0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

axon:
  axonserver:
    servers: localhost:8124  # Ensure this line is added to specify the Axon Server address
  eventhandling:
    processors:
      query:
        mode: tracking
        source: eventStore
        initial-segment-count: 1
  eventstore:
    jpa:
      schema-generation:
        enabled: true


management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    endpoint: http://localhost:9411/api/v2/spans # Zipkin Server URL
  prometheus:
    metrics:
      export:
        enabled: true

resilience4j:
  retry:
    instances:
      myRetry:
        max-attempts: 3 # Nombre maximum de tentatives
        wait-duration: 500ms # Durée entre chaque tentative
  rate-limiter:
    instances:
      myRateLimiter:
        limit-for-period: 5 # Nombre de requêtes par période
        limit-refresh-period: 1s # Période de rafraîchissement (1 seconde)
        timeout-duration: 500ms # Durée de timeout pour une requête